settings:
  clusterName: "cloud-labs"
  interruptionQueue: "cloud-labs-karpenter"
serviceAccount:
  name: karpenter
serviceAccount:
  name: karpenter
aws:
  defaultRegion: "us-east-1"
controller:
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
