nodeSelector:
  cloudlabs.infra-services: 'true'
dnsPolicy: Default
webhook:
  enabled: false
settings:
  clusterName: "cloud-labs"
  interruptionQueue: "cloud-labs-karpenter"
  enableZonalShift: true
env:
  - name: AWS_REGION
  - value: us-east-1
controller:
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
